# Generated by Django 6.1 on 2026-08-15 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresa',
            fields=[
                ('id_adresa', models.AutoField(db_column='IdAdresa', primary_key=True, serialize=False)),
                ('bloc', models.TextField(blank=True, db_column='Bloc', null=True)),
                ('scara', models.TextField(blank=True, db_column='Scara', null=True)),
                ('etaj', models.TextField(blank=True, db_column='Etaj', null=True)),
                ('apartament', models.TextField(blank=True, db_column='Apartament', null=True)),
            ],
            options={
                'db_table': 'Adrese',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id_card', models.AutoField(db_column='IdCard', primary_key=True, serialize=False)),
                ('numar_card', models.CharField(db_column='NumarCard', max_length=255, unique=True)),
                ('cvv', models.TextField(db_column='CVV')),
                ('data_expirare', models.DateTimeField(db_column='DataExpirare')),
            ],
            options={
                'db_table': 'Carduri',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(db_column='IdCategorie', primary_key=True, serialize=False)),
                ('denumire_categorie', models.CharField(db_column='DenumireCategorie', max_length=100, unique=True)),
                ('descriere_categorie', models.TextField(db_column='DescriereCategorie')),
            ],
            options={
                'db_table': 'Categorii',
            },
        ),
        migrations.CreateModel(
            name='Cos',
            fields=[
                ('id_cos', models.AutoField(db_column='idCos', primary_key=True, serialize=False)),
                ('cod_unic', models.TextField(db_column='CodUnic')),
                ('data_creare', models.DateTimeField(db_column='DataCreare')),
            ],
            options={
                'db_table': 'Cosuri',
            },
        ),
        migrations.CreateModel(
            name='Judet',
            fields=[
                ('id_judet', models.AutoField(db_column='IdJudet', primary_key=True, serialize=False)),
                ('denumire_judet', models.CharField(db_column='DenumireJudet', max_length=450, unique=True)),
            ],
            options={
                'db_table': 'Judete',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(db_column='IdMarca', primary_key=True, serialize=False)),
                ('nume_marca', models.CharField(db_column='NumeMarca', max_length=100)),
            ],
            options={
                'db_table': 'Marci',
            },
        ),
        migrations.CreateModel(
            name='Persoana',
            fields=[
                ('id_persoana', models.AutoField(db_column='IdPersoana', primary_key=True, serialize=False)),
                ('nume', models.TextField(db_column='Nume')),
                ('prenume', models.TextField(db_column='Prenume')),
                ('email', models.CharField(db_column='Email', max_length=450, unique=True)),
                ('tip_persoana', models.TextField(db_column='tipPersoana')),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=450, null=True)),
                ('rol', models.TextField(db_column='Rol')),
            ],
            options={
                'db_table': 'Persoane',
            },
        ),
        migrations.CreateModel(
            name='Tara',
            fields=[
                ('id_tara', models.AutoField(db_column='IdTara', primary_key=True, serialize=False)),
                ('denumire_tara', models.CharField(db_column='DenumireTara', max_length=450, unique=True)),
            ],
            options={
                'db_table': 'Tari',
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id_comanda', models.AutoField(db_column='IdComanda', primary_key=True, serialize=False)),
                ('eta', models.DateTimeField(blank=True, db_column='ETA', null=True)),
                ('pret_total', models.FloatField(db_column='PretTotal')),
                ('is_placed', models.BooleanField(db_column='IsPlaced')),
                ('adresa', models.ForeignKey(db_column='IdAdresa', on_delete=django.db.models.deletion.PROTECT, related_name='comenzi', to='core.adresa')),
                ('card', models.ForeignKey(blank=True, db_column='IdCard_CC', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comenzi', to='core.card')),
            ],
            options={
                'db_table': 'Comenzi',
            },
        ),
        migrations.CreateModel(
            name='Localitate',
            fields=[
                ('id_localitate', models.AutoField(db_column='IdLocalitate', primary_key=True, serialize=False)),
                ('denumire_localitate', models.TextField(db_column='DenumireLocalitate')),
                ('judet', models.ForeignKey(db_column='IdJudet', on_delete=django.db.models.deletion.PROTECT, related_name='localitati', to='core.judet')),
            ],
            options={
                'db_table': 'Localitati',
            },
        ),
        migrations.CreateModel(
            name='ModelAuto',
            fields=[
                ('id_model', models.AutoField(db_column='IdModel', primary_key=True, serialize=False)),
                ('nume_model', models.CharField(db_column='NumeModel', max_length=100)),
                ('an', models.IntegerField(blank=True, db_column='An', null=True)),
                ('marca', models.ForeignKey(db_column='IdMarca', on_delete=django.db.models.deletion.PROTECT, related_name='modele', to='core.marca')),
            ],
            options={
                'db_table': 'Modele',
            },
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id_produs', models.AutoField(db_column='IdProdus', primary_key=True, serialize=False)),
                ('nume', models.TextField(db_column='Nume')),
                ('descriere', models.TextField(blank=True, db_column='Descriere', null=True)),
                ('este_spray', models.BooleanField(db_column='EsteSpray')),
                ('valabil', models.BooleanField(db_column='Valabil')),
                ('categorie', models.ForeignKey(db_column='IdCategorie', on_delete=django.db.models.deletion.PROTECT, related_name='produse', to='core.categorie')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='PretProdus',
            fields=[
                ('id_pp', models.AutoField(db_column='idPP', primary_key=True, serialize=False)),
                ('pret', models.DecimalField(db_column='Pret', decimal_places=2, max_digits=18)),
                ('data_inceput', models.DateTimeField(db_column='DataInceput')),
                ('data_expirare', models.DateTimeField(blank=True, db_column='DataExpirare', null=True)),
                ('comision', models.DecimalField(blank=True, db_column='Comision', decimal_places=2, max_digits=18, null=True)),
                ('produs', models.ForeignKey(db_column='IdProdus', on_delete=django.db.models.deletion.PROTECT, related_name='preturi', to='core.produs')),
            ],
            options={
                'db_table': 'Preturi_Produs',
            },
        ),
        migrations.CreateModel(
            name='Imagine',
            fields=[
                ('id_imagine', models.AutoField(db_column='idImagine', primary_key=True, serialize=False)),
                ('fisier', models.BinaryField(db_column='Fisier')),
                ('produs', models.ForeignKey(db_column='IdProdus', on_delete=django.db.models.deletion.PROTECT, related_name='imagini', to='core.produs')),
            ],
            options={
                'db_table': 'Imagini',
            },
        ),
        migrations.CreateModel(
            name='Strada',
            fields=[
                ('id_strada', models.AutoField(db_column='IdStrada', primary_key=True, serialize=False)),
                ('denumire_strada', models.CharField(db_column='DenumireStrada', max_length=450, unique=True)),
                ('nr', models.IntegerField(db_column='Nr')),
                ('localitate', models.ForeignKey(db_column='IdLocalitate', on_delete=django.db.models.deletion.PROTECT, related_name='strazi', to='core.localitate')),
            ],
            options={
                'db_table': 'Strazi',
            },
        ),
        migrations.AddField(
            model_name='adresa',
            name='strada',
            field=models.ForeignKey(db_column='IdStrada', on_delete=django.db.models.deletion.PROTECT, related_name='adrese', to='core.strada'),
        ),
        migrations.CreateModel(
            name='Subcomanda',
            fields=[
                ('id_subcomanda', models.AutoField(db_column='IdSubcomanda', primary_key=True, serialize=False)),
                ('total_subproduse', models.IntegerField(db_column='TotalSubproduse')),
                ('comanda', models.ForeignKey(db_column='IdComanda', on_delete=django.db.models.deletion.CASCADE, related_name='subcomenzi', to='core.comanda')),
                ('produs', models.ForeignKey(db_column='IdProdus', on_delete=django.db.models.deletion.PROTECT, related_name='subcomenzi', to='core.produs')),
            ],
            options={
                'db_table': 'Subcomenzi',
            },
        ),
        migrations.CreateModel(
            name='Subprodus',
            fields=[
                ('id_subprodus', models.AutoField(db_column='IdSubprodus', primary_key=True, serialize=False)),
                ('valabil', models.BooleanField(db_column='Valabil')),
                ('cos', models.ForeignKey(blank=True, db_column='idCos', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subproduse', to='core.cos')),
                ('produs', models.ForeignKey(db_column='IdProdus', on_delete=django.db.models.deletion.PROTECT, related_name='subproduse', to='core.produs')),
            ],
            options={
                'db_table': 'SubProduse',
            },
        ),
        migrations.AddField(
            model_name='judet',
            name='tara',
            field=models.ForeignKey(db_column='IdTara', on_delete=django.db.models.deletion.PROTECT, related_name='judete', to='core.tara'),
        ),
        migrations.CreateModel(
            name='Utilizator',
            fields=[
                ('id_user', models.AutoField(db_column='IdUser', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=450, unique=True)),
                ('password', models.TextField(db_column='Password')),
                ('persoana', models.ForeignKey(db_column='IdPersoana', on_delete=django.db.models.deletion.PROTECT, related_name='useri', to='core.persoana')),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.AddField(
            model_name='produs',
            name='utilizator',
            field=models.ForeignKey(blank=True, db_column='IdUser', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produse', to='core.utilizator'),
        ),
        migrations.AddField(
            model_name='cos',
            name='utilizator',
            field=models.ForeignKey(db_column='IdUser', on_delete=django.db.models.deletion.PROTECT, related_name='cosuri', to='core.utilizator'),
        ),
        migrations.AddField(
            model_name='comanda',
            name='utilizator',
            field=models.ForeignKey(db_column='IdUser', on_delete=django.db.models.deletion.PROTECT, related_name='comenzi', to='core.utilizator'),
        ),
        migrations.CreateModel(
            name='AdresaUtilizator',
            fields=[
                ('id_au', models.AutoField(db_column='idAU', primary_key=True, serialize=False)),
                ('adresa', models.ForeignKey(db_column='IdAdresa', on_delete=django.db.models.deletion.PROTECT, related_name='adrese_useri', to='core.adresa')),
                ('utilizator', models.ForeignKey(db_column='IdUser', on_delete=django.db.models.deletion.PROTECT, related_name='adrese_useri', to='core.utilizator')),
            ],
            options={
                'db_table': 'Adrese_Useri',
            },
        ),
        migrations.CreateModel(
            name='UtilizatorCard',
            fields=[
                ('id_uc', models.AutoField(db_column='idUC', primary_key=True, serialize=False)),
                ('data_adaugarii', models.DateTimeField(db_column='DataAdaugarii')),
                ('card', models.ForeignKey(db_column='IdCard', on_delete=django.db.models.deletion.PROTECT, related_name='useri_carduri', to='core.card')),
                ('utilizator', models.ForeignKey(db_column='IdUser', on_delete=django.db.models.deletion.PROTECT, related_name='useri_carduri', to='core.utilizator')),
            ],
            options={
                'db_table': 'Useri_Carduri',
            },
        ),
        migrations.CreateModel(
            name='Vopsea',
            fields=[
                ('id_vopsea', models.AutoField(db_column='idVopsea', primary_key=True, serialize=False)),
                ('tip_vopsea', models.TextField(db_column='TipVopsea')),
                ('cod_culoare', models.CharField(blank=True, db_column='CodCuloare', max_length=100, null=True)),
                ('serie_caroserie', models.CharField(blank=True, db_column='SerieCaroserie', max_length=100, null=True)),
                ('model', models.ForeignKey(blank=True, db_column='IdModel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vopsele', to='core.modelauto')),
                ('produs', models.ForeignKey(db_column='IdProdus', on_delete=django.db.models.deletion.PROTECT, related_name='vopsele', to='core.produs')),
            ],
            options={
                'db_table': 'Vopsele',
                'constraints': [models.UniqueConstraint(fields=('cod_culoare', 'serie_caroserie'), name='UQ_CodCuloare_SerieCaroserie')],
            },
        ),
    ]
